### PR TITLE
Feat list_all

### PR DESCRIPTION
**Pull request by Hcreak**
为用户、角色、权限、分类、资源 添加 `list_all` 接口

### CODE REVIEW

**Comment by iGeeky** [comment]
Before you change your code to submit a new PR, it is best to use rebase to sync it from upstream.  This way, a small change will not always include all the commit history.
You will probably need to run the following commands: 
git remote add upstream https://github.com/iGeeky/wolf
git fetch upstream
git rebase upstream/master
Then execute the changes on the master after rebase and commit the PR.
image

**Comment by iGeeky** [comment]
@Hcreak Also what are these methods added to solve the problem? I don't really understand.
The listAll method seems to be a duplicate of the existing list method? If you need to query all the data at once, you can use list, passing in a large limit.
Also, it's not a good engineering practice to query all the data in one interface.

**Comment by Hcreak** [comment]
> Before you change your code to submit a new PR, it is best to use rebase to sync it from upstream. This way, a small change will not always include all the commit history.
> You will probably need to run the following commands:
> git remote add upstream https://github.com/iGeeky/wolf
> git fetch upstream
> git rebase upstream/master
> Then execute the changes on the master after rebase and commit the PR.

Thank you for your guidance. I‘m worrying about this problem.

**Comment by Hcreak** [comment]
@iGeeky  
Is such that, My colleague does need to query all permissions under the specified application at one time at work.
I see you have a `list_all` method for the application, Realized it on other interfaces.


The `list_all` methods of `roles`, `permissions`, `resources`, and `categorys` are all restricted to specific applications. I think this implementation is necessary, at least in my work. What do you think?

**Comment by iGeeky** [comment]
> @iGeeky
> Is such that, My colleague does need to query all permissions under the specified application at one time at work.
> I see you have a `list_all` method for the application, Realized it on other interfaces.
> 
> The `list_all` methods of `roles`, `permissions`, `resources`, and `categorys` are all restricted to specific applications. I think this implementation is necessary, at least in my work. What do you think?

@Hcreak  Using the `list` interface, passing in a large limit value, would that also meet your needs?
The application's list method has some permission controls. The application's listAll is not actually added for querying all data, it is added because of permission issues.

**Comment by Hcreak** [comment]
Wait a minute, I may need to tidy up

**Comment by Hcreak** [comment]
@iGeeky  
Ok, if you feel that this does not meet your specifications, I will not submit this PR again, please close

**Comment by Hcreak** [comment]
> @Hcreak Using the `list` interface, passing in a large limit value, would that also meet your needs?
We feel this is not elegant enough, LOL~

**Comment by iGeeky** [comment]
> > @Hcreak Using the `list` interface, passing in a large limit value, would that also meet your needs?
> 
> We feel this is not elegant enough, LOL~
An interface that returns all the data is also not elegant, and there are performance issues when the data volume is large, which should be avoided at all costs.  Consider, for example, a data volume of 10,000 items, or more.

**Pull request closed without merging**
